version: '3'
services:
  redis:
    image: redis:latest
    ports:
      - 6379:6379
  app:
    build: app
    command: node-dev app.js
    ports:
      - 4000:4000
    environment:
      REDIS_RUL: redis
      PORT: 4000
    volumes:
      - ./app:/src/
      - nodemodules:/src/node_modules
    links:
      - redis
    depends_on:
      - redis

volumes:
  nodemodules: {}